version: "3.8"
services:
  hello-postgres:
    image: postgres:15.3-bookworm
    container_name: hello-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgresql-data:/var/lib/postgresql/data/pgdata
volumes:
  postgresql-data:
networks:
  hello-network:
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/16
